### ISSUE TITLE
请教一下关于论文中的一些问题

### ISSUE THREAD

**Issue by luyvlei** [AmingWu/IIOD#3]
Disentangled Layer1 中使用了一个GRL层和判别器来训练DSR，但是据我了解对抗训练的方法可以用于得到域不变的特征，为什么这边可以用来得到domain-specific的特征呢

**Comment by AmingWu** [comment]
你好，理想情况下，GRL可以将源域和目标域特征进行对齐，但对齐后的特征仍然会带有对齐域的特性，这里，解耦主要是为了缓解对齐域对检测的影响。

**Comment by luyvlei** [comment]
所以这里GRL层的作用在于将Source 和 target 在特征层面对齐，那么对齐后的特征为什么称之为Domain specific的特征呢？
